### PR TITLE
SCT-792: add structured_query searching

### PR DESCRIPTION
**Pull request by JamesJeffryes**
This PR adds a mongo-style structured query interface to the search method. I'll need this for feature sets but I anticipate this being generally useful

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
I also added in the GenomeAnnotationAPI and tweaked the tests to make them compatible with new style genomes

**Comment by JamesJeffryes** [comment]
@scanon Would you be able to review?

**Comment by scanon** [comment]
I think this looks good.  My only concern is that we are sanity checking this structure query.  It looks like you are but I'm wondering if there are edge cases that could slip through and are there any risks.

**Comment by JamesJeffryes** [comment]
So looking back at my code, I'm not doing much in the way of validating the input to Structure query. I'll add some exceptions and tests. Only risk I can think of is that it is possible to pass in complex queries that are not very performant.

**Comment by scanon** [comment]
Looks good.

**Pull request merged**
